mask = imread('additionals/lanes578-closed.png');
load('additionals/578_tangent.mat');

%video = VideoWriter('roadSoupFilm.avi');
%video.FrameRate = 10;
%open(video);

yawMap = roadSoapFilm (tangent, 255 - mask, ...
                       'thresh', 0.01, ...
                       'sizeContour', 20, ...
                       'sizeBody', 10, ...
                       'verbose', 1);

%                        'thresh', [0.03 0.016 0.008 0.004 0.002 0.001], ...
%                        'sizeContour', [60 40 20 15 10 5], ...
%                        'sizeBody', [64 32 16 8 4 2], ...

%close(video)

imagesc(yawMap);
