% This function adds all the required paths to Matlab pathdef
%   It should be called in the beginning of the pipeline.
%

% check if everything hasn't already been set up
global CITY_PATHS_SET;
if isempty(CITY_PATHS_SET)
    CITY_PATHS_SET = true;

    % check that rootPathsSetup.m has been executed
    if ~exist ('CITY_SRC_PATH', 'var')
        % if not, check if that script is the parent dir. If so, execute it
        if exist ('rootPathsSetup.m', 'file')
            run 'rootPathsSetup.m';
        else
            error ('CITY_SRC_PATH is not set. Execute rootPathSetup.m first');
        end
    end

    % add all sub-directories from src/
    addpath( [ ...
        CITY_SRC_PATH ':' ...
        CITY_SRC_PATH 'background:' ...
        CITY_SRC_PATH 'car:' ...
        CITY_SRC_PATH 'car/segmentation:' ...
        CITY_SRC_PATH 'carCounting:' ...
        CITY_SRC_PATH 'detector:' ...
        CITY_SRC_PATH 'detector/extra:' ...
        CITY_SRC_PATH 'detector/opencv_cascade:' ...
        CITY_SRC_PATH 'detector/violajones:' ...
        CITY_SRC_PATH 'detector/multimodel:' ...
        CITY_SRC_PATH 'detector/fromback:' ...
        CITY_SRC_PATH 'extra:' ...
        CITY_SRC_PATH 'extra/videoDownload:' ...
        CITY_SRC_PATH 'geometry:' ...
        CITY_SRC_PATH 'io:' ...
        CITY_SRC_PATH 'io/export_fig:' ...
        CITY_SRC_PATH 'io/tightfig:' ...
        CITY_SRC_PATH 'pipeline:' ...
        CITY_SRC_PATH 'utilities' ] ...
    );

    fprintf('subdirPathsSetup note: have added the whole dir tree to pathdef. \n');

end

